### pubspec.yaml
name: frontend
description: A new Flutter project

environment:
  sdk: ">=2.17.0 <4.0.0" # Ajusta según tu versión de Dart instalada

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  logger: ^2.4.0 # Versión del paquete Logger

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
