name: frontend
description: "Catalogo de películas."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
    http: ^0.13.5
  image_picker: ^0.8.4+4
  logger: ^2.4.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
flutter_test:
    sdk: flutter
    flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  # Enable generation of localized Strings from arb files.
  generate: true

